services:
  broker:
    container_name: broker
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_BROKER_ID: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    hostname: broker
    image: confluentinc/cp-server:5.5.1
    ports:
    - published: 9092
      target: 9092
    - published: 9101
      target: 9101
  postgres:
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: postgres
    image: postgres:11.2
    ports:
    - published: 5432
      target: 5432
    volumes:
    - /Users/gauravedekar/Code/learning/datastreamer/environment/db/init.sql:/docker-entrypoint-initdb.d/init.sql:rw
    - /Users/gauravedekar/Code/learning/datastreamer/environment/db/postgresql.conf:/etc/postgresql.conf:rw
  prometheus:
    image: grafana/grafana
    ports:
    - published: 3000
      target: 3000
    - published: 9090
      target: 9090
    volumes:
    - /Users/gauravedekar/Code/learning/datastreamer/environment/db/prometheus.yml:/etc/prometheus/prometheus.yml:rw
  zookeeper:
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
    - published: 2181
      target: 2181
version: '3'

